name: Format code

on: 
  workflow_call:
    inputs:
      black_args:
        default: '--verbose'
        required: false
        type: string
        description: 'The options to pass to black'
      
      isort_args:
        default: ''
        required: false
        type: string
        description: 'The options to pass to isort'
      
      commiter_username:
        default: 'Formatter'
        required: false
        type: string
        description: 'The display name for the account used to push changes'
      
      commiter_email:
        default: 'github-actions[bot]@users.noreply.github.com'
        required: false
        type: string
        description: 'The email for the account used to push changes'

jobs:
  format:
    name: Format code

    permissions:
      contents: write

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install pip
      run: |
        python -m pip install --upgrade pip

    - name: Format with black
      id: format
      uses: rickstaa/action-black@v1.3.3
      with:
        black_args: '. ${{inputs.black_args}}'
    
    - name: Sort imports with isort
      id: isort
      uses: isort/isort-action@v1.1.0
      with: 
        configuration: '${{inputs.isort_args}}'
    
    - name: Check for file changes
      env:
        FILES_CHANGED: ${{steps.format.outputs.is_formatted == 'true' || contains(steps.isort.outputs.isort-result, 'Fixing')}}
      run: echo $FILES_CHANGED
    
    - name: Create pull request
      if: $FILES_CHANGED
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: "Format Python code with psf/black push"
        commit-message: ":art: Format Python code with psf/black"
        body: |
          There appear to be some python formatting errors in ${{ github.sha }}. This pull request
          uses the [psf/black](https://github.com/psf/black) formatter to fix these issues.
        base: ${{ github.head_ref }} # Creates pull request onto pull request or commit branch
        branch: actions/black

    - name: Commit formated file
      if: steps.format.outputs.is_formatted == 'true' || contains(steps.isort.outputs.isort-result, 'Fixing')
      run: |
        git config --global user.name "${{inputs.commiter_username}}"
        git config --global user.email ${{inputs.commiter_email}}

        git add .
        git commit -m "Formated code"
        git push