name: Format code

on: 
  workflow_call:
    inputs:
      black_args:
        default: '--verbose'
        required: false
        type: string
        description: 'The options to pass to black'
      
      isort_args:
        default: ''
        required: false
        type: string
        description: 'The options to pass to isort'
      
      commit_changes:
        default: false
        required: false
        type: boolean
        description: 'Wether or not to commit the changes directly instead of making a pull request'
      
      pull_request_title:
        default: 'Format code with black and isort'
        required: false
        type: string
        description: 'The title of the pull request created by the action'
      
      pull_request_body:
        default: 'There are some python formatting issues in ${{ github.sha }}. This pull request fixes those using [black](https://pypi.org/project/black/) along with [isort](https://pypi.org/project/isort/).'
        required: false
        type: string
        description: 'The body of the pull request created by the action'
      
      commit_message:
        default: 'Formated code with black and isort'
        required: false
        type: string
        description: 'The message for the commit with the formated file changes. Used both in the pull request and when commiting directly'

      commiter_username:
        default: 'Formatter'
        required: false
        type: string
        description: 'The display name for the account used to push changes'
      
      commiter_email:
        default: 'github-actions[bot]@users.noreply.github.com'
        required: false
        type: string
        description: 'The email for the account used to push changes'

jobs:
  format:
    name: Format code

    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install pip
      run: |
        python -m pip install --upgrade pip

    - name: Format with black
      id: format
      uses: rickstaa/action-black@v1.3.3
      with:
        black_args: '. ${{inputs.black_args}}'
    
    - name: Sort imports with isort
      id: isort
      uses: isort/isort-action@v1.1.0
      with: 
        configuration: '${{inputs.isort_args}}'
    
    - name: Check for file changes
      id: files_changed
      run: echo FILES_CHANGED=${{steps.format.outputs.is_formatted == 'true' || contains(steps.isort.outputs.isort-result, 'Fixing')}} >> $GITHUB_OUTPUT

    - name: Create Pull Request
      if: (steps.files_changed.outputs.FILES_CHANGED == 'true' && (!inputs.commit_changes))
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: ${{ inputs.pull_request_title }}
        commit-message: ${{ inputs.commit_message }}
        body: ${{ inputs.pull_request_body }}

    - name: Commit formated file
      if: (steps.files_changed.outputs.FILES_CHANGED == 'true' && inputs.commit_changes)
      run: |
        git config --global user.name "${{inputs.commiter_username}}"
        git config --global user.email ${{inputs.commiter_email}}

        git add .
        git commit -m ${{ inputs.commit_message }}
        git push