name: Format code

on: 
  workflow_call:
    inputs:
      black_args:
        default: '--verbose'
        required: false
        type: string
        description: 'The options to pass to black'
      
      isort_args:
        default: ''
        required: false
        type: string
        description: 'The options to pass to isort'
      
      commiter_username:
        default: 'Formatter'
        required: false
        type: string
        description: 'The display name for the account used to push changes'
      
      commiter_email:
        default: 'github-actions[bot]@users.noreply.github.com'
        required: false
        type: string
        description: 'The email for the account used to push changes'

jobs:
  format:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install pip
      run: |
        python -m pip install --upgrade pip

    - name: Format with black
      id: format
      uses: rickstaa/action-black@v1.3.3
      with:
        black_args: '. ${{inputs.black_args}}'
    
    - name: Sort imports with isort
      id: isort
      uses: isort/isort-action@v1.1.0
      with: 
        configuration: '${{inputs.isort_args}}'

    - name: Commit formated file
      if: steps.format.outputs.is_formatted == 'true' || contains(steps.isort.outputs.isort-result, 'Fixing')
      run: |
        git config --global user.name "${{inputs.commiter_username}}"
        git config --global user.email ${{inputs.commiter_email}}

        git add .
        git commit -m "Formated code"
        git push